### PR TITLE
add rich text support for basic/large image

### PR DESCRIPTION
**Pull request by Natkeeran**
# What does this Pull Request do?
This PR adds rich text support to basic and large image annotations.

# How should this be tested?
* Get the PR
* Use the following contexts
* Test basic and large images
* Test uncommon text in the edit boxes

### Basic image context
```
$context = new stdClass();
$context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
$context->api_version = 3;
$context->name = 'basic_image';
$context->description = '';
$context->tag = '';
$context->conditions = array(
  'islandora_context_condition_content_models' => array(
    'values' => array(
      0 => TRUE,
    ),
    'options' => array(
      'islandora_cmodels' => array(
        'islandora:sp_basic_image' => 'islandora:sp_basic_image',
      ),
    ),
  ),
);
$context->reactions = array(
  'block' => array(
    'blocks' => array(
      'views-2311609f0bf3cb72feb08a3542345a82' => array(
        'module' => 'views',
        'delta' => '2311609f0bf3cb72feb08a3542345a82',
        'region' => 'content',
        'weight' => '-10',
      ),
    ),
  ),
  'css_module' => array(
    'sites/all/modules/islandora_web_annotations' => array(
      'sites/all/modules/islandora_web_annotations/css/base/base.css' => 'sites/all/modules/islandora_web_annotations/css/base/base.css',
      'sites/all/modules/islandora_web_annotations/css/basic_image/basic_image.css' => 'sites/all/modules/islandora_web_annotations/css/basic_image/basic_image.css',
      'sites/all/modules/islandora_web_annotations/lib/css/theme-dark/annotorious-dark.css' => 'sites/all/modules/islandora_web_annotations/lib/css/theme-dark/annotorious-dark.css',
    ),
  ),
  'js_module' => array(
    'sites/all/modules/islandora_web_annotations' => array(
      'sites/all/modules/islandora_web_annotations/js/base/base.js' => 'sites/all/modules/islandora_web_annotations/js/base/base.js',
      'sites/all/modules/islandora_web_annotations/js/basic_image/basic_image.js' => 'sites/all/modules/islandora_web_annotations/js/basic_image/basic_image.js',
      'sites/all/modules/islandora_web_annotations/lib/js/tinymce/js/tinymce/tinymce.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/tinymce/js/tinymce/tinymce.min.js',
      'sites/all/modules/islandora_web_annotations/lib/js/jquery.blockUI.js' => 'sites/all/modules/islandora_web_annotations/lib/js/jquery.blockUI.js',
      'sites/all/modules/islandora_web_annotations/lib/js/annotorious.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/annotorious.min.js',
    ),
  ),
);
$context->condition_mode = 0;
```

### Large image context 
```
$context = new stdClass();
$context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
$context->api_version = 3;
$context->name = 'large_image';
$context->description = '';
$context->tag = '';
$context->conditions = array(
  'islandora_context_condition_content_models' => array(
    'values' => array(
      0 => TRUE,
    ),
    'options' => array(
      'islandora_cmodels' => array(
        'islandora:sp_large_image_cmodel' => 'islandora:sp_large_image_cmodel',       
      ),
    ),
  ),
);
$context->reactions = array(
  'block' => array(
    'blocks' => array(
      'views-2311609f0bf3cb72feb08a3542345a82' => array(
        'module' => 'views',
        'delta' => '2311609f0bf3cb72feb08a3542345a82',
        'region' => 'content',
        'weight' => '-10',
      ),
    ),
  ),
  'css_module' => array(
    'sites/all/modules/islandora_web_annotations' => array(
      'sites/all/modules/islandora_web_annotations/css/large_image/large_image.css' => 'sites/all/modules/islandora_web_annotations/css/large_image/large_image.css',
      'sites/all/modules/islandora_web_annotations/css/base/base.css' => 'sites/all/modules/islandora_web_annotations/css/base/base.css',
      'sites/all/modules/islandora_web_annotations/lib/css/theme-dark/annotorious-dark.css' => 'sites/all/modules/islandora_web_annotations/lib/css/theme-dark/annotorious-dark.css',
    ),
  ),
  'js_module' => array(
    'sites/all/modules/islandora_web_annotations' => array(
      'sites/all/modules/islandora_web_annotations/js/large_image/large_image.js' => 'sites/all/modules/islandora_web_annotations/js/large_image/large_image.js',
      'sites/all/modules/islandora_web_annotations/js/base/base.js' => 'sites/all/modules/islandora_web_annotations/js/base/base.js',
      'sites/all/modules/islandora_web_annotations/lib/js/tinymce/js/tinymce/tinymce.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/tinymce/js/tinymce/tinymce.min.js',
      'sites/all/modules/islandora_web_annotations/lib/js/jquery.blockUI.js' => 'sites/all/modules/islandora_web_annotations/lib/js/jquery.blockUI.js',
      'sites/all/modules/islandora_web_annotations/lib/js/annotorious.min.js' => 'sites/all/modules/islandora_web_annotations/lib/js/annotorious.min.js',
    ),
  ),
);
$context->condition_mode = 0;

```
# Interested parties
@MarcusBarnes @kimpham54

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
@Natkeeran With the block-quote feature, some CSS adjustments will be necessary to the display.  The block-quotes are very large in proportion to the annotation display box for basic image and the text is too light-colored. 

Example:

untitled

**Comment by MarcusBarnes** [comment]
Appears to work as expected except for some styling adjustments to the annotation display blox  as noted above and this one (from large image):

untitled2

**Comment by Natkeeran** [comment]
@MarcusBarnes 

Thank you.  I will turn off the option for quote.  It is not a plain HTML feature.

**Comment by MarcusBarnes** [comment]
@Natkeeran I've just pushed a couple of CSS additions that help resolve the additional minor changes we discussed off-thread.   Please review and if the changes are acceptable to you, please merge this pull-request.  I reviewed the earlier commits and they worked as described.

**Pull request merged**
